/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/init": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Авторизация пользователя через Telegram */
    post: operations["AuthController_createUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pair": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["PairController_getPairInfo"];
    put?: never;
    post: operations["PairController_createPair"];
    delete: operations["PairController_deletePair"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pair/change-host": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PairController_changeHost"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pair/change-date": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PairController_changeDate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/geo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["GeoController_createGeo"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить пользователя по Telegram ID */
    get: operations["UserController_getUserByTelegramId"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/change-name": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Изменить имя пользователя */
    post: operations["UserController_changeName"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/change-avatar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Изменить аватар пользователя (поле file в body) */
    post: operations["UserController_changeAvatar"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/geo-approval": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Изменить approveGeo пользователя */
    post: operations["UserController_setGeoApproval"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wishlist": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["WishlistController_getMyWishlist"];
    put?: never;
    post: operations["WishlistController_createWishlistItem"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wishlist/partner": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["WishlistController_getPartnerWishlist"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wishlist/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["WishlistController_deleteWishlistItem"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wishlist/{id}/book": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["WishlistController_bookItem"];
    delete: operations["WishlistController_unbookItem"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/joint-gift": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["JointGiftController_getAll"];
    put?: never;
    post: operations["JointGiftController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/joint-gift/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["JointGiftController_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/joint-gift/{id}/contribute": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["JointGiftController_contribute"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/joint-gift/{id}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["JointGiftController_complete"];
    trace?: never;
  };
  "/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Публичная статистика приложения */
    get: operations["StatsController_getStats"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateUserDto: {
      /**
       * @description Строка инициализации Telegram
       * @example user=%7B%22id%22%3A1785199158%2C%22first_name%...
       */
      queryString: string;
      /**
       * @description Информация об устройстве
       * @example iPhone 15, iOS 17
       */
      deviceData: string;
    };
    CreateUserResponseDto: {
      accessToken: string;
      isRegistration: boolean;
      isPaired: boolean;
    };
    HttpErrorDto: {
      statusCode: number;
      message: string[];
      error: string;
    };
    GeoShortDto: {
      /** @example 59.19979582064842 */
      latitude: number;
      /** @example 39.8741692677707 */
      longitude: number;
      /**
       * Format: date-time
       * @example 2025-06-24T18:59:07.827Z
       */
      timestamp: string;
    };
    UserWithGeoDto: {
      id: string;
      username: string;
      avatarUrl: string;
      geo: components["schemas"]["GeoShortDto"] | null;
      /** @example false */
      approveGeo: boolean;
    };
    PairResponseDto: {
      user1: components["schemas"]["UserWithGeoDto"];
      user2: components["schemas"]["UserWithGeoDto"];
      isHost: boolean;
      /** Format: date-time */
      startDate: string;
      distance: number;
    };
    Pair: {
      /** @description ID первого пользователя (ObjectId) */
      person1: string;
      /** @description ID второго пользователя (ObjectId) */
      person2: string;
      /**
       * Format: date-time
       * @description Дата начала отношений
       */
      startDate: string;
      /**
       * Format: date-time
       * @description Дата создания записи
       */
      createdAt: string;
    };
    ChangeDateDto: {
      /**
       * Format: date-time
       * @description Дата начала отношений
       */
      date: string;
    };
    CreatePairDto: {
      /**
       * @description ID второго пользователя
       * @example 665f2b1c2e8b2c001e7e7e7e
       */
      partnerId: string;
      /**
       * Format: date-time
       * @description Дата начала отношений
       * @example 2025-06-08T14:42:55.589Z
       */
      date: string;
    };
    CreateGeoDto: {
      /**
       * @description Широта
       * @example 59.19979582064842
       */
      latitude: number;
      /**
       * @description Долгота
       * @example 39.8741692677707
       */
      longitude: number;
      /**
       * @description Высота
       * @example 126.56125999855198
       */
      altitude: number;
      /**
       * @description Курс
       * @example -1
       */
      course: number;
      /**
       * @description Скорость
       * @example -1
       */
      speed: number;
      /**
       * @description Горизонтальная точность
       * @example 34.81285378476917
       */
      horizontal_accuracy: number;
      /**
       * @description Вертикальная точность
       * @example 30
       */
      vertical_accuracy: number;
      /**
       * @description Точность курса
       * @example -1
       */
      course_accuracy: number;
      /**
       * @description Точность скорости
       * @example -1
       */
      speed_accuracy: number;
      /**
       * Format: date-time
       * @description Временная метка
       * @example 2025-06-24T18:59:07.827Z
       */
      timestamp: string;
      /**
       * @description ID пользователя
       * @example 665f2b1c2e8b2c001e7e7e7e
       */
      userId: string;
    };
    UserPublicDto: {
      id: string;
      username: string;
      avatarUrl: string;
    };
    WishlistItemResponseDto: {
      /** @description ID элемента вишлиста */
      id: string;
      /** @description Название подарка */
      title: string;
      /** @description Описание */
      description?: string;
      /** @description Ссылка на товар */
      link?: string;
      /** @description URL картинки */
      imageUrl?: string;
      /** @description Цена */
      price?: number;
      /** @description Забронирован ли подарок партнёром (bookedBy не раскрывается) */
      isBooked: boolean;
      /**
       * Format: date-time
       * @description Дата добавления
       */
      createdAt: string;
    };
    PartnerWishlistItemResponseDto: {
      /** @description ID элемента вишлиста */
      id: string;
      /** @description Название подарка */
      title: string;
      /** @description Описание */
      description?: string;
      /** @description Ссылка на товар */
      link?: string;
      /** @description URL картинки */
      imageUrl?: string;
      /** @description Цена */
      price?: number;
      /** @description Забронирован ли подарок текущим пользователем */
      isBooked: boolean;
      /**
       * Format: date-time
       * @description Дата добавления
       */
      createdAt: string;
    };
    CreateWishlistItemDto: {
      /** @description Название подарка */
      title: string;
      /** @description Описание */
      description?: string;
      /** @description Ссылка на товар */
      link?: string;
      /** @description Цена */
      price?: number;
    };
    ShareResponseDto: {
      userId: string;
      percent: number;
      amount: number;
      contributed: number;
    };
    ContributionResponseDto: {
      userId: string;
      amount: number;
      /** Format: date-time */
      date: string;
    };
    JointGiftResponseDto: {
      id: string;
      createdById: string;
      title: string;
      description?: string;
      link?: string;
      imageUrl?: string;
      price: number;
      shares: components["schemas"]["ShareResponseDto"][];
      contributions: components["schemas"]["ContributionResponseDto"][];
      /** @enum {string} */
      status: "active" | "funded" | "completed";
      /** @description Прогресс накопления 0–100 */
      progress: number;
      /** Format: date-time */
      fundedAt?: string;
      /** Format: date-time */
      completedAt?: string;
      /** Format: date-time */
      createdAt: string;
    };
    CreateJointGiftDto: {
      /** @description Название подарка */
      title: string;
      /** @description Описание */
      description?: string;
      /** @description Ссылка на товар */
      link?: string;
      /** @description Общая цена подарка */
      price: number;
      /** @description Доля партнёра в процентах (1–99). Доля хоста = 100 - partnerPercent */
      partnerPercent: number;
    };
    ContributeDto: {
      /** @description Сумма взноса */
      amount: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_createUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
    responses: {
      /** @description Пользователь зарегистрирован */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateUserResponseDto"];
        };
      };
      /** @description Некорректные данные */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
    };
  };
  PairController_getPairInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Информация о паре */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PairResponseDto"];
        };
      };
    };
  };
  PairController_createPair: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePairDto"];
      };
    };
    responses: {
      /** @description Пара создана */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Pair"];
        };
      };
    };
  };
  PairController_deletePair: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Пара удалена */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": boolean;
        };
      };
    };
  };
  PairController_changeHost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Хост изменен */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Pair"];
        };
      };
    };
  };
  PairController_changeDate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangeDateDto"];
      };
    };
    responses: {
      /** @description Дата изменена */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Pair"];
        };
      };
    };
  };
  GeoController_createGeo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateGeoDto"];
      };
    };
    responses: {
      /** @description Запись о гео успешно добавлена */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UserController_getUserByTelegramId: {
    parameters: {
      query: {
        /** @description ID пользователя Telegram */
        telegramId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Пользователь найден */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserPublicDto"];
        };
      };
      /** @description Пользователь не найден */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
    };
  };
  UserController_changeName: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": unknown;
      };
    };
    responses: {
      /** @description Имя успешно изменено */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  UserController_changeAvatar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Аватар успешно изменён */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  UserController_setGeoApproval: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": unknown;
      };
    };
    responses: {
      /** @description approveGeo успешно изменён */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  WishlistController_getMyWishlist: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Свой вишлист */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WishlistItemResponseDto"][];
        };
      };
    };
  };
  WishlistController_createWishlistItem: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["CreateWishlistItemDto"];
      };
    };
    responses: {
      /** @description Желание добавлено */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WishlistItemResponseDto"];
        };
      };
    };
  };
  WishlistController_getPartnerWishlist: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Вишлист партнёра */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PartnerWishlistItemResponseDto"][];
        };
      };
    };
  };
  WishlistController_deleteWishlistItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Желание удалено */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": boolean;
        };
      };
    };
  };
  WishlistController_bookItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Подарок забронирован */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": boolean;
        };
      };
    };
  };
  WishlistController_unbookItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Бронь снята */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": boolean;
        };
      };
    };
  };
  JointGiftController_getAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Все совместные подарки пары */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JointGiftResponseDto"][];
        };
      };
    };
  };
  JointGiftController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["CreateJointGiftDto"];
      };
    };
    responses: {
      /** @description Подарок создан */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JointGiftResponseDto"];
        };
      };
    };
  };
  JointGiftController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Подарок удалён (только active) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": boolean;
        };
      };
    };
  };
  JointGiftController_contribute: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContributeDto"];
      };
    };
    responses: {
      /** @description Взнос внесён */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JointGiftResponseDto"];
        };
      };
    };
  };
  JointGiftController_complete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Подарок завершён */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JointGiftResponseDto"];
        };
      };
    };
  };
  StatsController_getStats: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
